version: '2'
services:
  jenkins:
    image: jenkins:v1
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - /home/ubuntu/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
